[package]
name = "rock-fmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.24.3"
tree-sitter-rock = { path = "../tree-sitter-rock" }
anyhow = "1.0.89"
